#!/bin/sh

set -eu

cd "${MESON_DIST_ROOT}"

# Delete everything we do not want to have in the release tarballs:
rm -rf \
   debian/ \
   testcases/.gitignore \
   travis/ \
   .clang-format \
   .editorconfig \
   mwm-bar/.gitignore \
   .travis.yml \
   logo.svg \
   README.md \
   release.sh

mkdir build
cd build
meson .. -Dprefix=/usr -Ddocs=true -Dmans=true
ninja
cp *.1 ../man/
cp *.html ../docs/
cd ..
rm -rf build
